---
swagger: "2.0"
info:
  version: "v1.0.0"
  title: "Alert Grapher"
host: "localhost"
basePath: "/api"
schemes:
- "http"
- "https"
paths:
  /alerts:
    get:
      summary: "Read All Alerts"
      operationId: "alertsGET"
      produces:
      - "application/json"
      parameters: []
      responses:
        200:
          description: "OK"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Alert"
      x-swagger-router-controller: "Default"
definitions:
  Alert:
    type: "object"
    properties:
      id:
        type: "string"
        example: "ac463592-dbd2-4ca3-a333d-48fhf5j5c871"
      count:
        type: "integer"
        example: 1
      alias:
        type: "string"
        example: "host_down"
      message:
        type: "string"
        example: "WebServer3 is down"
      status:
        type: "string"
        example: "closed"
      isSeen:
        type: "boolean"
        example: true
      acknowledged:
        type: "boolean"
        example: true
      snoozed:
        type: "boolean"
        example: false
      createdAt:
        type: "integer"
        example: 1349698149317
      updatedAt:
        type: "integer"
        example: 1349698149317
      tinyId:
        type: "string"
        example: "324"
      tags:
        type: "array"
        items:
          type: "string"
      owner:
        type: "string"
        example: "kili@opsgenie.com"
      teams:
        type: "array"
        example:
        - "operations"
        - "developers"
        items:
          type: "string"
      recipients:
        type: "array"
        example:
        - "kili@opsgenie.com"
        items:
          type: "string"
      entity:
        type: "string"
        example: ""
      details:
        type: "object"
        example:
          ip: "192.168.1.87"
        properties: {}
      source:
        type: "string"
        example: "fili@opsgenie.com"
      description:
        type: "string"
        example: "WebServer3 is down due to failure in WAN-1 connection."
      systemData:
        $ref: "#/definitions/SystemData"
  SystemData:
    type: "object"
    properties:
      integrationType:
        type: "string"
        example: "API"
      integrationId:
        type: "string"
        example: "95225ed3-03fb-4cdd-a035-44052d6f4496"
      integrationName:
        type: "string"
        example: "API"
      ackTime:
        type: "integer"
        example: 18171
      acknowledgedBy:
        type: "string"
        example: "kili@opsgenie.com"
      closeTime:
        type: "integer"
        example: 24737
      closedBy:
        type: "string"
        example: "fili@opsgenie.com"
