/**
 * qwer
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: Qwer
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface Service {
    appname?: string;

    language?: Service.LanguageEnum;

}
export namespace Service {
    export enum LanguageEnum {
        Java = <any> 'java',
        Node = <any> 'node',
        Python = <any> 'python',
        Perl = <any> 'perl',
        Go = <any> 'go',
        Nginx = <any> 'nginx',
        Busybox = <any> 'busybox'
    }
}
