swagger: "2.0"
info:
  title: "Alert Grapher"
  version: "v1.0.0"
schemes:
- http
- https
host: localhost:8080
paths:
  /alerts:
    get:
      summary: Read All Alerts
      produces:
      - application/json
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/AlertList'
definitions:
  Alert:
    type: object
    properties:
      id:
        type: string
      count:
        type: integer
      alias:
        type: string
      message:
        type: string
      status:
        type: string
      isSeen:
        type: boolean
      acknowledged:
        type: boolean
      snoozed:
        type: boolean
      createdAt:
        type: integer
      updatedAt:
        type: integer
      tinyId:
        type: string
      tags:
        type: array
        items:
          type: string
      owner:
        type: string
      teams:
        type: array
        items:
          type: string
      recipients:
        type: array
        items:
          type: string
      entity:
        type: string
      details:
        type: object
      source:
        type: string
      description:
        type: string
      # actions:
      #   type: array
      #   items:
      #     type: object
      #     properties:
      #       key:
      #         type: string
      systemData:
        $ref: '#/definitions/SystemData'
  AlertList:
    type: array
    items:
      $ref: '#/definitions/Alert'
  SystemData:
    type: object
    properties:
      integrationType:
        type: string
      integrationId:
        type: string
      integrationName:
        type: string
      ackTime:
        type: integer
      acknowledgedBy:
        type: string
      closeTime:
        type: integer
      closedBy:
        type: string
